### ISSUE TITLE
[Crash] Unexpected Exception

### ISSUE THREAD

**Issue by 77wisher77** [TheFloydman/Mystcraft-BoP-Disabler#1]
BoP version: `7.0.1.2419`
Mystcraft Version: `0.13.7.0.2`

Server Crashes on startup with Mystcraft BoP disabler installed, with this crash log

<details>
<summary>
Crash Log
</summary>

[crash-2019-01-10_01.17.16-server.txt](https://github.com/TheFloydman/Mystcraft-BoP-Disabler/files/2741442/crash-2019-01-10_01.17.16-server.txt)

</details>

**Comment by TheFloydman** [comment]
Ah yes, I've recently learned that I can't use the Minecraft class on a server. Until I get a fix up, you can get around this by removing the mod and copying the symbols.cfg after running on a client.

**Comment by 77wisher77** [comment]
Not sure i'll actually use it :P 
the worlds being flat doenst bother me so much. I'm more concerned with server crashes from tps overload

**Comment by TheFloydman** [comment]
Server-friendly code is up. Good luck!

https://minecraft.curseforge.com/projects/mystcraft-bop-disabler/files/2658274
